"""Show, per variant, what actually differs from its seed.

Criterion six is "are the variants genuinely different?" That should be a
diff, not a claim. This prints what moved in each of the three dimensions the
brief names -- facts, framing, placement -- and confirms the two things that
must NOT move: the grader and the feature contract.
"""

from __future__ import annotations

import difflib
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENVS = ROOT / "environments"
SEEDS = {"A": "A1-crm-ref-archive", "C": "C1-attachment-fetch"}


def digest(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


def grader_digest(env: Path) -> str:
    h = hashlib.sha256()
    for f in sorted((env / "tests").iterdir()):
        h.update(f.read_bytes())
    return h.hexdigest()[:12]


def repo_files(env: Path) -> dict[str, str]:
    repo = env / "environment" / "repo"
    return {
        str(p.relative_to(repo)).replace("\\", "/"): digest(p)
        for p in sorted(repo.rglob("*")) if p.is_file()
    }


def toml_value(env: Path, key: str) -> str:
    for line in (env / "task.toml").read_text(encoding="utf-8").splitlines():
        if line.startswith(f"{key} ="):
            return line.split("=", 1)[1].strip().strip('"')
    return ""


def main() -> None:
    lines = ["# Variant differences", "",
             "Generated by `tools/variant_diff.py`. Each variant reuses its "
             "seed's grader byte for byte and keeps the same feature contract; "
             "what moves is the scenario.", ""]

    for fam, seed_id in SEEDS.items():
        seed = ENVS / seed_id
        seed_grader = grader_digest(seed)
        seed_files = repo_files(seed)
        seed_instr = (seed / "instruction.md").read_text(encoding="utf-8").splitlines()

        lines += [f"## Family {fam} -- seed `{seed_id}`", "",
                  f"grader digest `{seed_grader}` (must be identical in every variant below)", ""]

        for env in sorted(ENVS.iterdir()):
            if not env.is_dir() or env.name == seed_id or env.name[0] != fam:
                continue
            g = grader_digest(env)
            files = repo_files(env)

            added = sorted(set(files) - set(seed_files))
            removed = sorted(set(seed_files) - set(files))
            changed = sorted(k for k in set(files) & set(seed_files)
                             if files[k] != seed_files[k])

            instr = (env / "instruction.md").read_text(encoding="utf-8").splitlines()
            sm = difflib.SequenceMatcher(None, seed_instr, instr)
            similarity = sm.ratio()

            lines += [
                f"### `{env.name}`", "",
                f"- varies: **{toml_value(env, 'varies')}**",
                f"- facts: {toml_value(env, 'variant_facts')}",
                f"- framing: {toml_value(env, 'variant_framing')}",
                f"- placement: {toml_value(env, 'variant_placement')}",
                f"- grader digest `{g}` "
                f"{'(identical to seed)' if g == seed_grader else '**DIFFERS FROM SEED**'}",
                f"- instruction overlap with seed: {similarity:.0%} "
                f"({len(instr)} lines vs {len(seed_instr)})",
            ]
            if added:
                lines.append(f"- repository files added: {', '.join('`%s`' % a for a in added)}")
            if removed:
                lines.append(f"- repository files removed: {', '.join('`%s`' % a for a in removed)}")
            if changed:
                lines.append(f"- repository files changed: {', '.join('`%s`' % c for c in changed)}")
            lines.append("")

    out = ROOT / "results" / "variant_differences.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\nwritten to {out}")


if __name__ == "__main__":
    main()
